### ISSUE TITLE
Implement Interest Button

### ISSUE THREAD

**Issue by francisngo** [cranebaes/gitbud#58]
Build interest button connection

**Comment by shaikathaque** [comment]
-On 'I want to work on this project' button click, make POST request to server sending an object with the project id (in an array--so can do multiple in future).
-Change button text to 'I am interested' to indicate it is selected.
-If POST request successful, update user's interestedIn property in the store.

**Comment by P-WM** [comment]
e.g.
{
  interested: [296]
}
